# Generated by Django 2.2.8 on 2020-07-03 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_agegroup_nutrationpoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NutrationPoint',
            new_name='NutritionPoint',
        ),
        migrations.RenameField(
            model_name='nutritionpoint',
            old_name='nutration_point',
            new_name='nutrition_point',
        ),
    ]
