# Generated by Django 2.2.8 on 2020-07-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
