# Generated by Django 2.2.8 on 2020-07-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
