# Generated by Django 2.2.8 on 2020-07-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'BCBD Member'), (2, 'Customer')], null=True),
        ),
    ]
