# Generated by Django 3.1.3 on 2020-11-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('number', models.CharField(max_length=200)),
                ('car_type', models.CharField(max_length=200)),
                ('amount', models.IntegerField(max_length=11)),
                ('date_now', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
