# Generated by Django 2.2.8 on 2020-07-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='size',
            field=models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], default=1),
        ),
    ]
