# Generated by Django 2.2.8 on 2020-07-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageproduct',
            old_name='unit',
            new_name='quantity',
        ),
    ]
