# Generated by Django 2.2.8 on 2020-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20200707_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Privet/Custom')], default=0),
        ),
    ]
