# Generated by Django 2.2.8 on 2020-07-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Privet/Custom')], default=1),
        ),
    ]
