# Generated by Django 2.2.8 on 2020-08-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20200721_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageproduct',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_to_package', to='packages.Package'),
        ),
        migrations.AlterField(
            model_name='packageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_to_product', to='products.Product'),
        ),
    ]
